emotions_bridge:
  ros__parameters:

      eyebrow_left_vert:
        pin: 0
        start_angle: 30 ##tested
        final_angle: 150  ##tested
        type: 'percentual'

        neutral: 150
        happy: 22
        sad: 105
        surprised: 30
        angry: 95
        suspicious: 115
        sleepy: 80


      eyebrow_right_vert: 
        pin: 3
        start_angle: 25 ##tested -> invertido, o final é o trilho recolhido
        final_angle: 150 ##tested  
        type: 'percentual'

        neutral: 25
        happy: 120
        sad: 80
        surprised: 150
        angry: 90
        suspicious: 150
        sleepy: 70


      eyebrow_left_rot:
        pin: 4
        start_angle: 115 ##tested
        final_angle: 175 ##tested
        type: 'rawangle'
    
        neutral: 145
        happy: 120
        sad: 10
        surprised: 130
        angry: 100
        suspicious: 120
        sleepy: 125


      eyebrow_right_rot:
        pin: 7
        start_angle: 105 ##tested
        final_angle: 165 ##tested 
        type: 'rawangle'

        neutral: 135
        happy: 43
        sad: 170
        surprised: 35
        angry: 75
        suspicious: 80
        sleepy: 35


      eyelid_left: 
        pin: 8
        start_angle: 10 ##tested - acho
        final_angle: 133 ##tested
        type: 'percentual'

        neutral: 10
        happy: 112
        sad: 105
        surprised: 125
        angry: 110
        suspicious: 100
        sleepy: 100


      eyelid_right:
        pin: 11
        start_angle: 35 ##tested
        final_angle: 140 #BARULHO 
        type: 'percentual'

        neutral: 140
        happy: 75
        sad: 78
        surprised: 60
        angry: 75
        suspicious: 90
        sleepy: 100


      eyes_ver: 
        pin: 15
        start_angle: 80
        final_angle: 125
        type: 'percentual'

        neutral: 65
        happy: 95
        sad: 95
        surprised: 95 
        angry: 95
        suspicious: 95
        sleepy: 95


      eyes_hor:
        pin: 16
        start_angle: 0
        final_angle: 120
        type: 'percentual'

        neutral: 43
        happy: 140
        sad: 120
        surprised: 140
        angry: 140
        suspicious: 130
        sleepy: 125


      jaw_right: 
        pin: 17
        start_angle: 108
        final_angle: 126
        type: 'percentual'

        neutral: 108
        happy: 108
        sad: 108
        surprised: 108
        angry: 108
        suspicious: 108
        sleepy: 108


      jaw_left: 
        pin: 18
        start_angle: 108
        final_angle: 126
        type: 'percentual'
        
        neutral: 108
        happy: 108
        sad: 108
        surprised: 108
        angry: 108
        suspicious: 108
        sleepy: 108